<a href="https://colab.research.google.com/github/ramank123/Yes-Bank-Stock-Closing-Price-Prediction/blob/main/Yes_Bank_Stock_Closing_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Load Libraries**

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from datetime import datetime
from sklearn.model_selection import train_test_split

## **Load Data**

In [6]:
df = pd.read_csv('/content/drive/MyDrive/AlmaBetter/Yes Bank Stock Closing Price Prediction/data_YesBank_StockPrices (1).csv')

In [7]:
df

Date   Open   High    Low  Close
0    Jul-05  13.00  14.00  11.25  12.46
1    Aug-05  12.58  14.88  12.55  13.42
2    Sep-05  13.48  14.87  12.27  13.30
3    Oct-05  13.20  14.47  12.40  12.99
4    Nov-05  13.35  13.88  12.88  13.41
..      ...    ...    ...    ...    ...
180  Jul-20  25.60  28.30  11.10  11.95
181  Aug-20  12.00  17.16  11.85  14.37
182  Sep-20  14.30  15.34  12.75  13.15
183  Oct-20  13.30  14.01  12.11  12.42
184  Nov-20  12.41  14.90  12.21  14.67

[185 rows x 5 columns]

In [8]:
df.head()

Date   Open   High    Low  Close
0  Jul-05  13.00  14.00  11.25  12.46
1  Aug-05  12.58  14.88  12.55  13.42
2  Sep-05  13.48  14.87  12.27  13.30
3  Oct-05  13.20  14.47  12.40  12.99
4  Nov-05  13.35  13.88  12.88  13.41

In [9]:
df.tail()

Date   Open   High    Low  Close
180  Jul-20  25.60  28.30  11.10  11.95
181  Aug-20  12.00  17.16  11.85  14.37
182  Sep-20  14.30  15.34  12.75  13.15
183  Oct-20  13.30  14.01  12.11  12.42
184  Nov-20  12.41  14.90  12.21  14.67

In [10]:
df.shape

(185, 5)

In [11]:
df.info

<bound method DataFrame.info of        Date   Open   High    Low  Close
0    Jul-05  13.00  14.00  11.25  12.46
1    Aug-05  12.58  14.88  12.55  13.42
2    Sep-05  13.48  14.87  12.27  13.30
3    Oct-05  13.20  14.47  12.40  12.99
4    Nov-05  13.35  13.88  12.88  13.41
..      ...    ...    ...    ...    ...
180  Jul-20  25.60  28.30  11.10  11.95
181  Aug-20  12.00  17.16  11.85  14.37
182  Sep-20  14.30  15.34  12.75  13.15
183  Oct-20  13.30  14.01  12.11  12.42
184  Nov-20  12.41  14.90  12.21  14.67

[185 rows x 5 columns]>

In [12]:
df.dtypes

Date      object
Open     float64
High     float64
Low      float64
Close    float64
dtype: object

In [13]:
df1 = df.drop('Date', axis=1)
df1

Open   High    Low  Close
0    13.00  14.00  11.25  12.46
1    12.58  14.88  12.55  13.42
2    13.48  14.87  12.27  13.30
3    13.20  14.47  12.40  12.99
4    13.35  13.88  12.88  13.41
..     ...    ...    ...    ...
180  25.60  28.30  11.10  11.95
181  12.00  17.16  11.85  14.37
182  14.30  15.34  12.75  13.15
183  13.30  14.01  12.11  12.42
184  12.41  14.90  12.21  14.67

[185 rows x 4 columns]

# **Split Data**

In [14]:
X=df1.drop('Close',axis=1)
X

Open   High    Low
0    13.00  14.00  11.25
1    12.58  14.88  12.55
2    13.48  14.87  12.27
3    13.20  14.47  12.40
4    13.35  13.88  12.88
..     ...    ...    ...
180  25.60  28.30  11.10
181  12.00  17.16  11.85
182  14.30  15.34  12.75
183  13.30  14.01  12.11
184  12.41  14.90  12.21

[185 rows x 3 columns]

In [15]:
y=df1['Close']
y

0      12.46
1      13.42
2      13.30
3      12.99
4      13.41
       ...  
180    11.95
181    14.37
182    13.15
183    12.42
184    14.67
Name: Close, Length: 185, dtype: float64

In [16]:
X.shape

(185, 3)

In [17]:
y.shape

(185,)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=51)

In [19]:
X_train

Open    High     Low
32    48.90   48.90   24.11
27    41.80   47.30   33.60
58    56.94   58.08   50.66
64    72.20   77.60   58.00
158  347.20  350.00  166.15
..      ...     ...     ...
105   83.45   94.98   80.80
180   25.60   28.30   11.10
149  307.20  319.00  300.65
16    22.80   28.47   21.40
57    50.67   59.48   48.80

[148 rows x 3 columns]

In [20]:
X_test

Open    High     Low
7     15.50   16.97   15.40
23    33.89   36.38   30.40
10    19.80   21.80   15.80
65    61.80   68.36   55.44
21    27.00   31.99   26.20
36    22.85   30.50   20.40
35    31.22   32.22   22.62
31    50.88   53.97   44.40
4     13.35   13.88   12.88
73    62.90   63.96   50.51
89    89.20   95.00   88.01
166  163.30  178.05  133.05
68    51.84   65.20   50.80
14    18.00   18.88   16.80
78    47.92   66.50   46.11
121  165.90  169.19  118.00
42    15.28   18.34   11.48
171   42.00   76.65   29.05
101   74.40   83.00   71.63
59    56.70   59.90   52.60
108  108.43  114.46  100.44
13    15.90   18.60   15.70
100   74.00   77.27   64.65
51    41.20   52.34   36.80
45    10.04   17.51    9.94
8     16.20   20.95   16.02
146  351.00  383.25  345.50
150  314.00  366.00  307.35
151  355.00  366.50  304.65
113  142.08  155.00  134.00
50    33.80   41.30   32.00
91   104.41  107.80   93.40
162  182.85  236.30  181.15
152  320.70  325.80  285.10
90    93.20  107.00   93.20
120  169.00  175.58  156.45
19    30.20   32.60   26.80

In [21]:
y_train

32      33.75
27      43.48
58      57.57
64      61.21
158    183.45
        ...  
105     88.14
180     11.95
149    315.05
16      25.32
57      57.10
Name: Close, Length: 148, dtype: float64

In [22]:
y_test

7       16.12
23      35.98
10      18.03
65      62.54
21      30.31
36      25.45
35      22.85
31      49.42
4       13.41
73      55.61
89      92.84
166    147.95
68      61.98
14      18.46
78      65.99
121    137.90
42      12.24
171     70.45
101     74.02
59      53.83
108    108.21
13      17.84
100     73.74
51      47.31
45      15.45
8       20.08
146    350.00
150    354.45
151    322.25
113    154.57
50      40.99
91      94.50
162    194.30
152    304.90
90     104.41
120    165.74
19      28.63
Name: Close, dtype: float64

# **Feature Scaling**

In [23]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)
X_train = ss.transform(X_train)
X_test = ss.transform(X_test)

In [24]:
X_train

array([[-0.60671351, -0.66437811, -0.80809952],
       [-0.67865198, -0.67944306, -0.70380284],
       [-0.52525079, -0.57794298, -0.5163106 ],
       [-0.37063374, -0.39415064, -0.43564277],
       [ 2.41571547,  2.1706564 ,  0.75294373],
       [ 0.06099709, -0.01780946,  0.04374829],
       [ 1.28293787,  1.18201933,  1.32553141],
       [-0.48897759, -0.33991684, -0.40992578],
       [-0.38380557, -0.40921559, -0.32343317],
       [-0.9786658 , -1.00710563, -0.96426978],
       [-0.16596372, -0.17947516, -0.43882992],
       [-0.38887166, -0.46015394, -0.42630113],
       [ 0.8432013 ,  1.05396728,  0.54248204],
       [-0.74552436, -0.29669928, -1.01207701],
       [ 0.43517845,  0.36248627,  0.50984125],
       [-0.43142681, -0.39330324, -0.3646463 ],
       [-0.91189474, -0.89694322, -0.86975435],
       [-0.43345325, -0.48632928, -0.59807743],
       [-0.46384978, -0.48454032, -0.39871581],
       [-0.26586701, -0.28116355, -0.16946094],
       [-0.48147977, -0.54404686, -0.474

In [27]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [28]:
lr.coef_

array([-52.48103407,  57.07433116,  93.85723269])

In [29]:
lr.intercept_

108.10891891891892

In [30]:
X_test[0,:]

array([-0.94512828, -0.96501794, -0.90382387])

In [31]:
lr.predict([X_test[0,:]])

array([17.8020681])

In [32]:
lr.predict(X_test)

array([ 17.8020681 ,  33.92654794,  18.52374447,  62.10009491,
        30.89882274,  26.32212641,  25.08565513,  48.78592009,
        14.68539729,  54.06533564,  95.4424228 , 147.12913188,
        60.91195873,  18.94322146,  58.85724699, 125.46115181,
        14.61176891,  49.86218175,  79.96754059,  57.33621968,
       108.4961324 ,  18.77476457,  69.90108681,  45.21783963,
        15.36357169,  20.20818566, 376.73589199, 347.78860928,
       323.47059934, 147.00593279,  38.26876755,  99.79294181,
       217.65182596, 299.67186013, 105.11761606, 166.90807767,
        30.14394261])

In [33]:
y_test

7       16.12
23      35.98
10      18.03
65      62.54
21      30.31
36      25.45
35      22.85
31      49.42
4       13.41
73      55.61
89      92.84
166    147.95
68      61.98
14      18.46
78      65.99
121    137.90
42      12.24
171     70.45
101     74.02
59      53.83
108    108.21
13      17.84
100     73.74
51      47.31
45      15.45
8       20.08
146    350.00
150    354.45
151    322.25
113    154.57
50      40.99
91      94.50
162    194.30
152    304.90
90     104.41
120    165.74
19      28.63
Name: Close, dtype: float64

In [34]:
lr.score(X_test, y_test)

0.9936065208570741